# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "Politician" ("Pol_ID" BIGINT NOT NULL PRIMARY KEY,"Firstname" VARCHAR NOT NULL,"Lastname" VARCHAR NOT NULL,"Party" VARCHAR NOT NULL,"Constituency" VARCHAR NOT NULL);
create table "Rate" ("Rate_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"Time" BIGINT NOT NULL,"Rate" INTEGER NOT NULL,"Pol_ID" BIGINT NOT NULL);
alter table "Rate" add constraint "Pol_FK" foreign key("Pol_ID") references "Politician"("Pol_ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "Rate" drop constraint "Pol_FK";
drop table "Politician";
drop table "Rate";

